[tool.poetry]
name = "object-detection-infra"
version = "0.1.0"
description = "CDKTF code for object-detection-infra"
authors = ["Utt Assoratgoon"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
dynaconf = "^3.2.6"
cdktf = "^0.20.8"
cdktf-cdktf-provider-random = "^11.0.2"
cdktf-cdktf-provider-google = "^13.31.0"
cdktf-cdktf-provider-docker = "^11.0.0"
cdktf-cdktf-provider-gitlab = "^13.3.1"
cdktf-cdktf-provider-null = "^10.0.0"
cdktf-cdktf-provider-external = "^10.0.2"
inflection = "^0.5.1"
pydantic = "^2.8.2"
dvc = {extras = ["gs"], version = "^3.55.2"}
cdktf-cdktf-provider-google-beta = "^14.7.0"
cdktf-cdktf-provider-aws = "^19.39.0"

[tool.poetry.dev-dependencies]
darglint = ">=1.8.1"

[tool.black]
# Note: this needs to be consistent with `FORMAT/max-line-length` in .pylintrc
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"